# Generated by Django 5.2.4 on 2025-08-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admCode', models.CharField(blank=True, db_column='admCode', null=True)),
                ('linkNo', models.CharField(db_column='linkNo', max_length=100, null=True)),
                ('linkCode', models.CharField(db_column='linkCode', max_length=100)),
                ('linkName', models.CharField(db_column='linkName', max_length=250)),
                ('linkLengthOfficial', models.FloatField(db_column='linkLengthOfficial')),
                ('linkLengthActual', models.FloatField(db_column='linkLengthActual')),
                ('status', models.CharField(blank=True, db_column='status', max_length=10, null=True)),
                ('function', models.CharField(blank=True, db_column='function', max_length=10, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=10, null=True)),
                ('wti', models.IntegerField(blank=True, db_column='wti', null=True)),
                ('mca2', models.IntegerField(blank=True, db_column='mca2', null=True)),
                ('mca3', models.IntegerField(blank=True, db_column='mca3', null=True)),
                ('mca4', models.IntegerField(blank=True, db_column='mca4', null=True)),
                ('mca5', models.IntegerField(blank=True, db_column='mca5', null=True)),
                ('projectNumber', models.CharField(blank=True, db_column='projectNumber', max_length=100, null=True)),
                ('cumesa', models.FloatField(blank=True, db_column='cumesa', null=True)),
                ('esa0', models.FloatField(blank=True, db_column='esa0', null=True)),
                ('aadt', models.IntegerField(blank=True, db_column='aadt', null=True)),
                ('accessStatus', models.CharField(blank=True, db_column='accessStatus', max_length=100, null=True)),
            ],
            options={
                'db_table': 'link',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pCode', models.CharField(max_length=15)),
                ('admNameEng', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kCode', models.CharField(max_length=15)),
                ('admNameEng', models.CharField(max_length=100)),
                ('province', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ebu.province')),
            ],
            options={
                'db_table': 'kabupaten',
            },
        ),
    ]
