# Generated by Django 5.2.4 on 2025-08-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admCode', models.CharField(max_length=15)),
                ('lgName', models.CharField(max_length=100)),
                ('emailId', models.CharField(blank=True, max_length=100)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('dbCloudLink', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
