# Generated by Django 5.2.5 on 2025-08-11 12:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admCode', models.CharField(max_length=50)),
                ('linkGeometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('linkNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments', to='ebu.link')),
            ],
            options={
                'db_table': 'alignment',
            },
        ),
    ]
