# Generated by Django 5.2.4 on 2025-08-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebu', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admCode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='user',
            name='admcode',
            field=models.CharField(default='TEMP', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
