# Generated by Django 5.2.5 on 2025-08-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebu', '0002_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admCode', models.CharField(max_length=50)),
                ('fileUrl', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'dbfile',
            },
        ),
        migrations.CreateModel(
            name='DrpFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admCode', models.CharField(max_length=50)),
                ('drpFile', models.FileField(upload_to='drp_files/')),
            ],
            options={
                'db_table': 'drpfile',
            },
        ),
    ]
