# Generated by Django 5.2.5 on 2025-08-11 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebu', '0003_remove_user_admcode_remove_user_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_code', models.CharField(max_length=50)),
                ('link_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments', to='ebu.link')),
            ],
        ),
    ]
